// Copyright (C) 2019-2021, Xiongfa Li.
// @author xiongfa.li
// @version V1.0
// Description:

package generator

import (
	"bytes"
	"fmt"
	"github.com/xfali/neve-gen/pkg/model"
	"io"
	"time"
)

const (
	header       = "Code generated by neve-gen (https://github.com/xfali/neve-gen). \n"
	headerTime   = "time: %s\n"
	headerSource = "source: %s\n\n"
)

var headWriter = map[string]func(w io.Writer, source string) error{
	model.TemplateCodeGo:   WriteGoHeader,
	model.TemplateCodeYaml: WriteYamlHeader,
}

func WriteHeader(w io.Writer, code, source string) error {
	hw := headWriter[code]
	if hw != nil {
		return hw(w, source)
	}
	return nil
}

func WriteGoHeader(w io.Writer, source string) error {
	buf := bytes.Buffer{}
	buf.WriteString("// ")
	buf.WriteString(fmt.Sprintf(header))
	buf.WriteString("// ")
	buf.WriteString(fmt.Sprintf(headerTime, time.Now().Format(time.RFC3339)))
	buf.WriteString("// ")
	buf.WriteString(fmt.Sprintf(headerSource, source))
	_, err := w.Write(buf.Bytes())
	return err
}

func WriteYamlHeader(w io.Writer, source string) error {
	buf := bytes.Buffer{}
	buf.WriteString("# ")
	buf.WriteString(fmt.Sprintf(header))
	buf.WriteString("# ")
	buf.WriteString(fmt.Sprintf(headerTime, time.Now().Format(time.RFC3339)))
	buf.WriteString("# ")
	buf.WriteString(fmt.Sprintf(headerSource, source))
	_, err := w.Write(buf.Bytes())
	return err
}
