// Copyright (C) 2019-2021, Xiongfa Li.
// @author xiongfa.li
// @version V1.0
// Description:

package generator

import (
	"fmt"
	"io"
	"time"
)

const (
	header = "// Code generated by neve-gen(https://github.com/xfali/neve-gen). \n// time: %s\n// source: %s\n\n"
)

func WriteHeader(w io.Writer, source string) error {
	_, err := w.Write([]byte(fmt.Sprintf(header, time.Now().Format(time.RFC3339), source)))
	return err
}
